import type { User, Listing, Message, Transaction, Comment, Review, Offer } from './types';

export const MOCK_REVIEWS: Review[] = [
    {
        _id: "review001",
        authorId: "user456",
        listingId: "item333",
        transactionId: "tx1002",
        rating: 5,
        text: "Great seller, very responsive and item was as described. Highly recommended!",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    },
    {
        _id: "review002",
        authorId: "user789",
        listingId: "item-add-4",
        transactionId: "tx1003", // Assuming this tx exists for demo
        rating: 4,
        text: "Smooth transaction and fast shipping. The shoes were in great condition.",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    }
];

export const MOCK_USERS: User[] = [
    {
        _id: "user123",
        firstName: "Ram",
        lastName: "Thapa",
        phone: "+9779800000000",
        email: "ram@example.com",
        photo: "https://picsum.photos/seed/user123/200/200",
        isVerified: true,
        kycStatus: "verified",
        walletBalance: 25000.00,
        location: { lat: 27.7, lng: 85.3 },
        savedItems: ['item222', 'item333'],
        reviews: [MOCK_REVIEWS[1]],
        joinedAt: "2024-01-15T10:00:00Z",
        address: {
            state: "Bagmati",
            district: "Kathmandu",
            municipality: "Kathmandu",
            ward: "10"
        }
    },
    {
        _id: "user456",
        firstName: "Sita",
        lastName: "Sharma",
        phone: "+9779811111111",
        email: "sita@example.com",
        photo: "https://picsum.photos/seed/user456/200/200",
        isVerified: false,
        kycStatus: "unverified",
        walletBalance: 150000.00,
        location: { lat: 27.71, lng: 85.32 },
        savedItems: ['item111'],
        reviews: [],
        joinedAt: "2024-03-22T14:30:00Z",
    },
    {
        _id: "user789",
        firstName: "Hari",
        lastName: "Kumar",
        phone: "+9779822222222",
        photo: "https://picsum.photos/seed/user789/200/200",
        isVerified: true,
        kycStatus: "verified",
        walletBalance: 80000.00,
        location: { lat: 27.69, lng: 85.31 },
        savedItems: [],
        reviews: [MOCK_REVIEWS[0]],
        joinedAt: "2023-11-05T09:00:00Z",
         address: {
            state: "Bagmati",
            district: "Lalitpur",
            municipality: "Patan",
            ward: "5"
        }
    }
];

export const MOCK_COMMENTS: Comment[] = [
    {
        _id: "comment001",
        authorId: "user456",
        text: "Is the battery health still good?",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    },
    {
        _id: "comment002",
        authorId: "user789",
        text: "Can you deliver to Bhaktapur?",
        timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    },
];

export const MOCK_LISTINGS: Listing[] = [
    {
        _id: "item789",
        title: "Used iPhone 12",
        description: "Excellent condition, 128GB, unlocked. Comes with original box and charger. Minor scratches on the side, screen is perfect.",
        price: 75000,
        priceType: "negotiable",
        category: "Electronics",
        images: ["https://picsum.photos/seed/item789_1/600/400", "https://picsum.photos/seed/item789_2/600/400"],
        sellerId: "user123",
        status: "available",
        location: { lat: 27.7, lng: 85.3 },
        createdAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(), // 10 mins ago
        comments: MOCK_COMMENTS,
        condition: 'like-new',
    },
    {
        _id: "item111",
        title: "Vintage Wooden Chair",
        description: "A beautiful handcrafted wooden chair from the 70s. Perfect for a study or living room. Strong and sturdy.",
        price: 12000,
        priceType: "negotiable",
        category: "Furniture",
        images: ["https://picsum.photos/seed/item111_1/600/400"],
        sellerId: "user789",
        status: "available",
        location: { lat: 27.69, lng: 85.31 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(), // 2 days ago
        condition: 'used',
    },
    {
        _id: "item444",
        title: "Sony WH-1000XM4 Headphones",
        description: "Noise-cancelling headphones in pristine condition. Used for 6 months. Comes with the case and all accessories.",
        price: 18000,
        priceType: "fixed",
        category: "Electronics",
        images: ["https://picsum.photos/seed/item444_1/600/400"],
        sellerId: "user456",
        status: "available",
        location: { lat: 27.71, lng: 85.32 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(), // 1 day ago
        condition: 'like-new',
    },
    {
        _id: "item555",
        title: "Modern Coffee Table",
        description: "Sleek and stylish coffee table with a glass top and metal frame. Perfect for any modern living room. Dimensions: 40x20x18 inches.",
        price: 8500,
        priceType: "negotiable",
        category: "Furniture",
        images: ["https://picsum.photos/seed/item555_1/600/400", "https://picsum.photos/seed/item555_2/600/400"],
        sellerId: "user123",
        status: "available",
        location: { lat: 27.7, lng: 85.3 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(), // 3 days ago
        condition: 'used',
    },
    {
        _id: "item222",
        title: "Mountain Bike",
        description: "21-speed mountain bike, great for trails. Recently serviced. Brand: Trek. Frame size: Medium.",
        price: 45000,
        priceType: "negotiable",
        category: "Vehicles",
        images: ["https://picsum.photos/seed/item222_1/600/400", "https://picsum.photos/seed/item222_2/600/400", "https://picsum.photos/seed/item222_3/600/400"],
        sellerId: "user123",
        status: "available",
        location: { lat: 27.7, lng: 85.3 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(), // 1 week ago
        condition: 'used',
    },
    {
        _id: "item666",
        title: "Royal Enfield Classic 350",
        description: "Well-maintained 2018 model Classic 350. Low kilometers. All papers clear. A true classic for bike enthusiasts.",
        price: 250000,
        priceType: "negotiable",
        category: "Vehicles",
        images: ["https://picsum.photos/seed/item666_1/600/400"],
        sellerId: "user789",
        status: "available",
        location: { lat: 27.69, lng: 85.31 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(), // 4 days ago
        condition: 'used',
    },
    {
        _id: "item777",
        title: "North Face Puffer Jacket",
        description: "Authentic North Face jacket, Size M. Very warm and comfortable, perfect for winter. Rarely used.",
        price: 6500,
        priceType: "fixed",
        category: "Clothing",
        images: ["https://picsum.photos/seed/item777_1/600/400"],
        sellerId: "user456",
        status: "available",
        location: { lat: 27.71, lng: 85.32 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(), // 5 days ago
        condition: 'like-new',
    },
    {
        _id: "item888",
        title: "Samsung 4K Smart TV - 43 inch",
        description: "Crystal clear 4K UHD display. Smart TV with all popular apps like Netflix, YouTube, etc. No scratches or dead pixels. Includes remote.",
        price: 55000,
        priceType: "fixed",
        category: "Electronics",
        images: ["https://picsum.photos/seed/item888_1/600/400"],
        sellerId: "user789",
        status: "available",
        location: { lat: 27.69, lng: 85.31 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(), // 6 days ago
        condition: 'like-new',
    },
    {
        _id: "item999",
        title: "Hardcover Novel Set (5 Books)",
        description: "A collection of 5 popular fantasy novels in hardcover format. Includes books from Brandon Sanderson and Patrick Rothfuss. Like new condition.",
        price: 2500,
        priceType: "fixed",
        category: "Other",
        images: ["https://picsum.photos/seed/item999_1/600/400"],
        sellerId: "user123",
        status: "available",
        location: { lat: 27.7, lng: 85.3 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(), // 8 days ago
        condition: 'new',
    },
    {
        _id: "item101",
        title: "Acoustic Guitar",
        description: "Yamaha F310 acoustic guitar. Great for beginners. Comes with a carrying bag and some picks. Good sound quality.",
        price: 11000,
        priceType: "negotiable",
        category: "Other",
        images: ["https://picsum.photos/seed/item101_1/600/400"],
        sellerId: "user456",
        status: "available",
        location: { lat: 27.71, lng: 85.32 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 9).toISOString(), // 9 days ago
        condition: 'used',
    },
    {
        _id: "item121",
        title: "Comfy Office Chair",
        description: "Ergonomic office chair with lumbar support and adjustable height. Perfect for working from home. No tears or damage.",
        price: 7000,
        priceType: "fixed",
        category: "Furniture",
        images: ["https://picsum.photos/seed/item121_1/600/400"],
        sellerId: "user789",
        status: "available",
        location: { lat: 27.69, lng: 85.31 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(), // 10 days ago
        condition: 'like-new',
    },
    {
        _id: "item333",
        title: "Leather Jacket",
        description: "Men's leather jacket, size L. Worn only a few times. No signs of wear. Very warm.",
        price: 9000,
        priceType: "negotiable",
        category: "Clothing",
        images: ["https://picsum.photos/seed/item333_1/600/400"],
        sellerId: "user789",
        status: "sold",
        location: { lat: 27.69, lng: 85.31 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(), // 1 month ago
        condition: 'like-new',
    },
    {
        _id: "item-new-1",
        title: "Vintage Seiko 5 Automatic Watch",
        description: "Classic men's automatic watch from the 1980s. Keeps good time, recently serviced. A perfect piece for collectors or daily wear.",
        price: 15000,
        priceType: "negotiable",
        category: "Other",
        images: ["https://picsum.photos/seed/item-new-1/600/400"],
        sellerId: "user789",
        status: "available",
        location: { lat: 27.69, lng: 85.31 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
        condition: 'used',
    },
    {
        _id: "item-new-2",
        title: "PUBG Mobile Account - Level 70",
        description: "High-level PUBG Mobile account with many rare skins, including M416 Glacier skin. Good KD ratio. Safe transfer via dummy social media account.",
        price: 9500,
        priceType: "fixed",
        category: "Other",
        images: ["https://picsum.photos/seed/item-new-2/600/400"],
        sellerId: "user456",
        status: "available",
        location: { lat: 27.71, lng: 85.32 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
        condition: 'for-parts', // Represents digital item, for-parts as placeholder
    },
    {
        _id: "item-new-3",
        title: "100 US Dollars for Exchange",
        description: "Selling 100 USD in cash. Crisp notes. Exchange rate is negotiable, but better than market rate. Only available for pickup in Kathmandu.",
        price: 13200,
        priceType: "negotiable",
        category: "Other",
        images: ["https://picsum.photos/seed/item-new-3/600/400"],
        sellerId: "user123",
        status: "available",
        location: { lat: 27.7, lng: 85.3 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
        condition: 'new',
    },
    {
        _id: "item-new-4",
        title: "Handmade Crochet Bee Keychain",
        description: "Cute and soft handmade crochet bee. Perfect as a keychain or a small gift. Made with high-quality cotton yarn.",
        price: 500,
        priceType: "fixed",
        category: "Other",
        images: ["https://picsum.photos/seed/item-new-4/600/400"],
        sellerId: "user456",
        status: "available",
        location: { lat: 27.71, lng: 85.32 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
        condition: 'new',
    },
    {
        _id: "item-new-5",
        title: "Canon EOS 80D DSLR with Kit Lens",
        description: "Excellent condition Canon 80D camera body with 18-55mm kit lens. Low shutter count. Perfect for both photography and videography. Includes battery, charger, and camera bag.",
        price: 85000,
        priceType: "negotiable",
        category: "Electronics",
        images: ["https://picsum.photos/seed/item-new-5-1/600/400", "https://picsum.photos/seed/item-new-5-2/600/400"],
        sellerId: "user789",
        status: "available",
        location: { lat: 27.69, lng: 85.31 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
        condition: 'like-new',
    },
    {
        _id: "item-new-6",
        title: "Trekking Package for ABC",
        description: "Looking for a partner for Annapurna Base Camp trek. All gear included (jacket, sleeping bag, poles). Price is per person for a 7-day trek. Guide and permits extra.",
        price: 18000,
        priceType: "fixed",
        category: "Other",
        images: ["https://picsum.photos/seed/item-new-6/600/400"],
        sellerId: "user123",
        status: "available",
        location: { lat: 27.7, lng: 85.3 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
        condition: 'new',
    },
    {
        _id: "item-new-7",
        title: "NIU NQi-GT Electric Scooter",
        description: "2021 model NIU electric scooter. Top speed 70km/h, range of 100km. Well-maintained with regular servicing. Digital display and smart features.",
        price: 320000,
        priceType: "negotiable",
        category: "Vehicles",
        images: ["https://picsum.photos/seed/item-new-7/600/400"],
        sellerId: "user456",
        status: "available",
        location: { lat: 27.71, lng: 85.32 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
        condition: 'like-new',
    },
    {
        _id: "item-new-8",
        title: "Designer Silk Saree",
        description: "Beautiful designer silk saree with intricate embroidery. Worn only once for a wedding. Perfect for special occasions. Dry cleaned and ready to wear.",
        price: 22000,
        priceType: "fixed",
        category: "Clothing",
        images: ["https://picsum.photos/seed/item-new-8-1/600/400", "https://picsum.photos/seed/item-new-8-2/600/400"],
        sellerId: "user789",
        status: "available",
        location: { lat: 27.69, lng: 85.31 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
        condition: 'like-new',
    },
    {
        _id: "item-new-9",
        title: "Playstation 4 Slim 1TB",
        description: "PS4 Slim 1TB console with one controller and all necessary cables. Excellent working condition. Comes with a few game discs like FIFA 20 and God of War.",
        price: 35000,
        priceType: "fixed",
        category: "Electronics",
        images: ["https://picsum.photos/seed/item-new-9/600/400"],
        sellerId: "user123",
        status: "available",
        location: { lat: 27.7, lng: 85.3 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
        condition: 'used',
    },
    {
        _id: "item-add-1",
        title: "DJI Mavic Air 2 Drone",
        description: "Like new condition DJI Mavic Air 2. Fly More Combo included with 3 batteries, carrying case, and extra propellers. No crash history. Amazing 4K video.",
        price: 98000,
        priceType: "negotiable",
        category: "Electronics",
        images: ["https://picsum.photos/seed/item-add-1/600/400"],
        sellerId: "user789",
        status: "available",
        location: { lat: 27.69, lng: 85.31 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
        condition: 'like-new',
    },
    {
        _id: "item-add-2",
        title: "Minimalist Study Desk",
        description: "Simple and elegant study desk with a white top and wooden legs. Perfect for a home office or student room. Dimensions: 120cm x 60cm.",
        price: 6000,
        priceType: "fixed",
        category: "Furniture",
        images: ["https://picsum.photos/seed/item-add-2/600/400"],
        sellerId: "user123",
        status: "available",
        location: { lat: 27.7, lng: 85.3 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
        condition: 'new',
    },
    {
        _id: "item-add-3",
        title: "2015 Suzuki Swift VXi",
        description: "Well-maintained Suzuki Swift, 2015 model. Manual transmission. Low mileage for its age. Regularly serviced. Bluebook clear.",
        price: 1850000,
        priceType: "negotiable",
        category: "Vehicles",
        images: ["https://picsum.photos/seed/item-add-3-1/600/400", "https://picsum.photos/seed/item-add-3-2/600/400"],
        sellerId: "user456",
        status: "available",
        location: { lat: 27.71, lng: 85.32 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
        condition: 'used',
    },
    {
        _id: "item-add-4",
        title: "Nike Air Jordan 1 Mid",
        description: "Barely used Air Jordan 1 Mid sneakers, 'Bred' colorway. Size UK 9 / US 10. Comes with original box. 100% authentic.",
        price: 16500,
        priceType: "fixed",
        category: "Clothing",
        images: ["https://picsum.photos/seed/item-add-4/600/400"],
        sellerId: "user123",
        status: "sold",
        location: { lat: 27.7, lng: 85.3 },
        createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
        condition: 'like-new',
    },
    {
        _id: "item-add-5",
        title: "Philips Air Fryer HD9216",
        description: "Healthy cooking with this Philips Air Fryer. Used for about a year, works perfectly. Great for making fries, chicken wings, and more with less oil.",
        price: 11000,
        priceType: "negotiable",
        category: "Other",
        images: ["https://picsum.photos/seed/item-add-5/600/400"],
        sellerId: "user789",
        status: "available",
        location: { lat: 27.69, lng: 85.31 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
        condition: 'used',
    },
    {
        _id: "item-add-6",
        title: "Yoga Mat and Blocks Set",
        description: "High-quality, non-slip yoga mat with two foam blocks. Mat is thick and comfortable. Great for home workouts or studio classes.",
        price: 2200,
        priceType: "fixed",
        category: "Other",
        images: ["https://picsum.photos/seed/item-add-6/600/400"],
        sellerId: "user456",
        status: "available",
        location: { lat: 27.71, lng: 85.32 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
        condition: 'new',
    },
    {
        _id: "item-add-7",
        title: "Cozy Pet Bed (Medium Size)",
        description: "Soft and comfortable bed for a medium-sized dog or cat. Washable cover. My dog has outgrown it. Clean and in good condition.",
        price: 1800,
        priceType: "fixed",
        category: "Other",
        images: ["https://picsum.photos/seed/item-add-7/600/400"],
        sellerId: "user123",
        status: "available",
        location: { lat: 27.7, lng: 85.3 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
        condition: 'used',
    },
    {
        _id: "item-add-8",
        title: "Sony FE 24-70mm f/2.8 GM Lens",
        description: "Professional-grade G Master standard zoom lens. In perfect condition with no scratches on the glass. Includes lens hood, caps, and original pouch. A versatile lens for portraits, landscapes, and video.",
        price: 150000,
        priceType: "negotiable",
        category: "Electronics",
        images: ["https://picsum.photos/seed/item-add-8/600/400"],
        sellerId: "user789",
        status: "available",
        location: { lat: 27.69, lng: 85.31 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 15).toISOString(),
        condition: 'like-new',
    },
    {
        _id: "item-add-9",
        title: "Spider-Man Comic Collection (20 comics)",
        description: "A collection of 20 modern Spider-Man comics. Mostly from the 'Amazing Spider-Man' series. All are bagged and boarded, in near-mint condition. Great for a starting collector.",
        price: 4500,
        priceType: "fixed",
        category: "Other",
        images: ["https://picsum.photos/seed/item-add-9/600/400"],
        sellerId: "user123",
        status: "available",
        location: { lat: 27.7, lng: 85.3 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
        condition: 'like-new',
    },
    {
        _id: "item-add-10",
        title: "JBL Flip 5 Portable Speaker",
        description: "Waterproof portable Bluetooth speaker in black. Great sound quality and long battery life. Used but in excellent working condition. Comes with charging cable.",
        price: 8000,
        priceType: "fixed",
        category: "Electronics",
        images: ["https://picsum.photos/seed/item-add-10/600/400"],
        sellerId: "user456",
        status: "available",
        location: { lat: 27.71, lng: 85.32 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
        condition: 'used',
    },
    {
        _id: "item-add-11",
        title: "Handmade Genuine Leather Backpack",
        description: "Stylish and durable backpack made from genuine leather. Can fit a 15-inch laptop. Multiple compartments for organization. Perfect for work or travel.",
        price: 7500,
        priceType: "negotiable",
        category: "Clothing",
        images: ["https://picsum.photos/seed/item-add-11/600/400"],
        sellerId: "user123",
        status: "available",
        location: { lat: 27.7, lng: 85.3 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
        condition: 'new',
    },
    {
        _id: "item-add-12",
        title: "Large Monstera Deliciosa Plant",
        description: "Healthy and thriving Monstera plant in a ceramic pot. About 3 feet tall with beautiful fenestrated leaves. Low maintenance and great for improving indoor air quality. Pickup only.",
        price: 3500,
        priceType: "fixed",
        category: "Other",
        images: ["https://picsum.photos/seed/item-add-12/600/400"],
        sellerId: "user456",
        status: "available",
        location: { lat: 27.71, lng: 85.32 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
        condition: 'new',
    },
    {
        _id: "item-add-13",
        title: "Professional Chef's Knife Set",
        description: "Set of 5 high-carbon stainless steel kitchen knives with a wooden block. Includes chef's knife, bread knife, santoku knife, utility knife, and paring knife. Very sharp and well-balanced.",
        price: 6000,
        priceType: "fixed",
        category: "Other",
        images: ["https://picsum.photos/seed/item-add-13/600/400"],
        sellerId: "user789",
        status: "available",
        location: { lat: 27.69, lng: 85.31 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
        condition: 'new',
    },
    {
        _id: "item-add-14",
        title: "Element Complete Skateboard",
        description: "Complete 8.0 inch Element skateboard. Good for beginners and intermediate skaters. Deck has some scratches from use but trucks and wheels are in great shape.",
        price: 5500,
        priceType: "negotiable",
        category: "Other",
        images: ["https://picsum.photos/seed/item-add-14/600/400"],
        sellerId: "user123",
        status: "available",
        location: { lat: 27.7, lng: 85.3 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 9).toISOString(),
        condition: 'used',
    },
    {
        _id: "item-add-15",
        title: "Custom 65% Mechanical Keyboard",
        description: "Custom-built 65% layout mechanical keyboard with hot-swappable PCB. Features Gateron Brown tactile switches and PBT keycaps. Aluminum case. Perfect for typing and gaming enthusiasts.",
        price: 14000,
        priceType: "negotiable",
        category: "Electronics",
        images: ["https://picsum.photos/seed/item-add-15/600/400"],
        sellerId: "user789",
        status: "available",
        location: { lat: 27.69, lng: 85.31 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
        condition: 'like-new',
    },
    {
        _id: "item-car-1",
        title: "Honda City 2019 Model",
        description: "Single owner, well-maintained Honda City. Perfect family car with great mileage. All papers are clear. Minor scratches on the bumper.",
        price: 2800000,
        priceType: "negotiable",
        category: "Vehicles",
        images: ["https://picsum.photos/seed/honda-city-1/600/400", "https://picsum.photos/seed/honda-city-2/600/400"],
        sellerId: "user789",
        status: "available",
        location: { lat: 27.69, lng: 85.31 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
        condition: 'used',
    },
    {
        _id: "item-drone-1",
        title: "DJI Mini 2 Drone Fly More Combo",
        description: "Excellent condition DJI Mini 2, perfect for beginners and travelers. Less than 10 hours of flight time. Comes with 3 batteries, charging hub, and carrying case.",
        price: 65000,
        priceType: "negotiable",
        category: "Electronics",
        images: ["https://picsum.photos/seed/dji-drone-1/600/400"],
        sellerId: "user123",
        status: "available",
        location: { lat: 27.7, lng: 85.3 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
        condition: 'like-new',
    },
    {
        _id: "item-laptop-1",
        title: "Dell XPS 15 Laptop",
        description: "Powerful Dell XPS 15 with 4K touchscreen display. Intel i7, 16GB RAM, 512GB SSD. Great for video editing and programming. Has a small dent on the corner but works perfectly.",
        price: 120000,
        priceType: "negotiable",
        category: "Electronics",
        images: ["https://picsum.photos/seed/dell-xps-1/600/400"],
        sellerId: "user456",
        status: "available",
        location: { lat: 27.71, lng: 85.32 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
        condition: 'used',
    },
    {
        _id: "item-cam-1",
        title: "Sony A7 III Mirrorless Camera (Body)",
        description: "Full-frame mirrorless camera, great for both photos and videos. Shutter count around 15k. Comes with original battery and charger. No scratches on sensor or screen.",
        price: 180000,
        priceType: "negotiable",
        category: "Electronics",
        images: ["https://picsum.photos/seed/sony-a7-1/600/400"],
        sellerId: "user789",
        status: "available",
        location: { lat: 27.69, lng: 85.31 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
        condition: 'like-new',
    },
    {
        _id: "item-console-1",
        title: "Nintendo Switch OLED",
        description: "Barely used Nintendo Switch OLED model. Comes with dock, joy-cons, and all original accessories. Screen protector applied since day one. Includes carrying case.",
        price: 42000,
        priceType: "fixed",
        category: "Electronics",
        images: ["https://picsum.photos/seed/switch-1/600/400", "https://picsum.photos/seed/switch-2/600/400"],
        sellerId: "user456",
        status: "available",
        location: { lat: 27.71, lng: 85.32 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
        condition: 'like-new',
    },
    {
        _id: "item-helmet-1",
        title: "AGV K1 Helmet - Soleluna",
        description: "AGV K1 Helmet with Valentino Rossi's Soleluna design. Size M. Used for a few months, never dropped. Clean interior and exterior. Comes with clear and smoke visors.",
        price: 18500,
        priceType: "fixed",
        category: "Other",
        images: ["https://picsum.photos/seed/agv-helmet-1/600/400"],
        sellerId: "user123",
        status: "available",
        location: { lat: 27.7, lng: 85.3 },
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
        condition: 'like-new',
    }
];

export const MOCK_MESSAGES: Message[] = [
    {
        _id: "msg001",
        chatId: "chat123",
        senderId: "user456",
        receiverId: "user123",
        message: "Is this item still available?",
        timestamp: "2024-10-06T08:15:00Z",
        status: 'read'
    },
    {
        _id: "msg002",
        chatId: "chat123",
        senderId: "user123",
        receiverId: "user456",
        message: "Yes, it is!",
        timestamp: "2024-10-06T08:16:00Z",
        status: 'read'
    },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
    {
        _id: "tx1001",
        buyerId: "user456",
        sellerId: "user123",
        itemId: "item789",
        amount: 75000,
        status: "escrow_held",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString()
    },
    {
        _id: "tx1002",
        buyerId: "user456",
        sellerId: "user789",
        itemId: "item333",
        amount: 9000,
        status: "released",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString()
    },
    {
        _id: "tx1003",
        buyerId: "user789",
        sellerId: "user123",
        itemId: "item-add-4",
        amount: 16500,
        status: "released",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString()
    }
];

export const MOCK_OFFERS: Offer[] = [
    {
        _id: "offer001",
        listingId: "item111", // Vintage Wooden Chair
        buyerId: "user123", // Ram
        sellerId: "user789", // Hari
        amount: 10000,
        status: "pending",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    },
    {
        _id: "offer002",
        listingId: "item789", // Used iPhone 12
        buyerId: "user456", // Sita
        sellerId: "user123", // Ram
        amount: 72000,
        status: "accepted",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    },
    {
        _id: "offer003",
        listingId: "item222", // Mountain Bike
        buyerId: "user789", // Hari
        sellerId: "user123", // Ram
        amount: 40000,
        status: "rejected",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    }
];